# Generated by Django 4.1 on 2024-11-02 05:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 5, 17, 39, 122220)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='imgid',
            field=models.ForeignKey(blank=True, default=16, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.images'),
        ),
    ]
