# Generated by Django 4.1 on 2024-11-17 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_customer_created_date_alter_customer_imgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 9, 45, 55, 485031)),
        ),
    ]
